config/routes.rb
Rails.application.routes.draw do
  get 'home/_header'
  get 'home/about'
  get 'home/profile'
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :posts

  get 'home/about'
  get 'home/profile'

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :posts

  validates :name, presence: true, length: { maximum: 16 }
  validates :name, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:about, :_header ]

  def _header
  end

  def about
  end

  def profile
    @username = current_user.name
    @posts = current_user.posts
    @postcount = @posts.length();
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show ] # If the user isnt logged in, show only show them...
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, alert: "Not Authorised To Edit This Post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :anonymous, :graphic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000">
    <%= link_to "backwatertruth.org", root_path, class:"navbar-brand", style:"color: #E5E8E8" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="color: #000000">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'About', home_about_path, class:"nav-link" %>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to 'Profile', home_profile_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/profile.html.erb
<div id="edit">
    <div class="card float-left" style="width: 18rem; position: absolute;">
        <div class="card-body">
            <h5 class="card-title"><%= @username %></h5>
            <h6 class="card-text text-muted"><%= @postcount %> Post<% if @postcount != 1 %>s<% end %></h6>
            <%= link_to "Back", :back, class:"card-link" %>
            <%= link_to "Edit", edit_user_registration_path, class:"card-link" %>
        </div>
    </div>
</div>

<div id="posts">
  <% @posts.each do |post| %>
    <div class="card w-50 text-center text-white", style="background-color: #000000">
      <div class="card-body">
        <% if post.anonymous == true %>
          <em class="user-tag" style="color: #8D9797" >anonymous</em>
        <% else %>
          <em class="user-tag" style="color: #8D9797"><%= User.find(post.user_id).name %></em>
        <% end %>
        <% if post.graphic == true %>
          <div class="dot">
            <span class="tooltiptext">Violent or gory post</span>
          </div>
        <% end %>
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text" id="card-text" ><%= post.content %></p>
        <%= link_to 'Read', post, class:"btn btn-outline-primary my-2 my-sm-0" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "", new_post_path, class:"button_plus" %>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_notice.erb
<div class="alert alert-dark alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v. 4.6.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Backwatertruth</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
  </head>
  <body> <!--style="background-color: #4E545C"-->
    
    <%= render 'home/header' %>

    <div class="container">
       <br/> 
      <% if notice %>
        <%= render 'layouts/notice' %>
      <% end %>

      <% if alert %>
        <%= render 'layouts/alert' %>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- personal -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="card w-50 text-center text-white", style="background-color: #000000">
      <div class="card-body">
        <h5 class="card-title">
            <div class="form-group" >
              <%= form.text_field :title, class:"form-control", placeholder:"Title", style:"background-color: black; color: white;" %>
          </div>
        </h5>
        <p class="card-text" id="card-text" >
            <div class="form-group" >
              <%= form.text_area :content, class:"form-control", id:"exampleFormControlTextarea1", rows:"16", placeholder:"Content", style:"background-color: black; color: white;" %>
            </div>
            <div class="custom-control custom-switch float-left">
              <%= form.check_box :anonymous, class:"custom-control-input anonymous", id:"anonymousSwitch"%>
              <label class="custom-control-label" for="anonymousSwitch">Anonymous</label>
            </div>
            <br/>
            <div class="custom-control custom-switch float-left">
              <%= form.check_box :graphic, class:"custom-control-input graphic", id:"graphicSwitch"%>
              <label class="custom-control-label" for="graphicSwitch">Graphic (gore/violence)</label>
            </div>
            <!-- I opted to submit the user_id within the create method in the post controller
                so that one cannot use inspect element to bypass restrictions -->
            <!--<div class="form-group" > 
              <%= form.number_field :user_id, id: :post_user_id, value:current_user.id, type: :hidden  %>
            </div>-->
            <br/>
            <br/>
            <div>
              <%= form.submit "Post", class:"btn btn-outline-primary savebtn" %>
              <%= link_to 'Back', root_path, class:"btn btn-outline-primary savebtn" %>
            </div>  
        </p>
      </div>
    </div>


<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <%= post.anonymous %>
  </p>

</div>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <div class="card w-50 text-center text-white", style="background-color: #000000">
      <div class="card-body">
        <% if post.anonymous == true %>
          <em class="user-tag" style="color: #8D9797" >anonymous</em>
        <% else %>
          <em class="user-tag" style="color: #8D9797"><%= User.find(post.user_id).name %></em>
        <% end %>
        <% if post.graphic == true %>
          <div class="dot">
            <span class="tooltiptext">Violent or gory post</span>
          </div>
        <% end %>
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text" id="card-text" ><%= post.content %></p>
        <%= link_to 'Read', post, class:"btn btn-outline-primary my-2 my-sm-0" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "", new_post_path, class:"button_plus" %>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div id="posts">
    <div class="card w-50 text-white", style="background-color: #000000">
      <div class="card-body">
        <% if @post.anonymous == true %>
          <em class="user-tag" style="color: #8D9797" >anonymous</em>
        <% else %>
          <% u = User.find(@post.user_id) %>
          <% if u == nil %>
            <em class="user-tag" style="color: #8D9797">[ deleted ]</em>
          <% else %>
            <em class="user-tag" style="color: #8D9797"><%= u.name %></em>
          <% end %>
        <% end %>
        <% if @post.graphic == true %>
          <div class="dot">
            <span class="tooltiptext">Violent or gory post</span>
          </div>
        <% end %>
        <h5 class="card-title text-center "><%= @post.title %></h5>
        <p class="card-text"><%= simple_format(@post.content) %></p>
        <div class="text-center">
          <%= link_to "Back", root_path, class:"btn btn-outline-primary my-2 my-sm-0" %>
          <% if @post.user == current_user  %>
            <br/>
            <br/>
            <a href="<%= edit_post_path(@post) %>"><button class="button_to btn btn-outline-warning my-2 my-sm-0"  >Edit</button></a>
            <form method="delete" action="<%= @post %>" class="button_to" >
              <div><input value="Delete" type="submit" class="btn btn-outline-danger my-2 my-sm-0"/></div>
            </form>
          <% end %>
        </div>
      </div>
    </div>
</div>